DROP TABLE IF EXISTS LIBRARY;

CREATE TABLE LIBRARY (
  library_id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(40) NOT NULL,
  type VARCHAR(40) NOT NULL);

DROP TABLE IF EXISTS BOOK;

CREATE TABLE BOOK (
  book_id INT AUTO_INCREMENT  PRIMARY KEY,
  title VARCHAR(40) NOT NULL,
  price DOUBLE NOT NULL,
  volume INT NOT NULL,
  library_id INT NOT NULL,
  FOREIGN KEY (LIBRARY_ID) REFERENCES LIBRARY(LIBRARY_ID));